window.huuperCopy = Object.assign({}, window.huuperCopy || {}, {
  battleplan: {
    wizard: {
      progressPrefix: "MISSION PHASE",
      statePriority: "PRIORITY",
      nextLabel: "NEXT",
      backLabel: "BACK",
      daysSuffix: "D",
      routineWord: "Routine",
      routineCountWord: "routines",
      labels: {
        priorityField: "Main Priority",
        whyField: "Why",
        durationField: "Priority Duration",
        objectiveField: "Objective",
        titleField: "Title",
        triggerField: "Trigger",
        cadenceField: "Cadence",
        timesPerWeek: "Times per week",
        summaryPriority: "Priority",
        summaryDuration: "Duration",
        summaryVisibility: "Visibility",
        summaryPillars: "Pillars",
      },
      placeholders: {
        priorityTitle: "E.g. Show up for the people I love.",
        priorityWhy: "Define your 'why' to keep course...",
        objective: "Define a concrete and measurable objective",
        routineTitle: "e.g. daily cold shower",
        routineTrigger: "e.g. right after I wake up",
      },
      actions: {
        addRoutine: "+ Add routine",
        removeRoutineAria: "Remove",
        expandRoutineAria: "Expand routine",
        collapseRoutineAria: "Collapse routine",
        deleteRoutine: {
          title: "Delete routine",
          meta: "This action cannot be undone.",
          cancelLabel: "Cancel",
          confirmLabel: "Delete",
        },
      },
      dayShort: {
        mon: "M",
        tue: "T",
        wed: "W",
        thu: "T",
        fri: "F",
        sat: "S",
        sun: "S",
      },
      errors: {
        saveFailed: "Save failed. Try again.",
        priorityRequired: "Priority is required",
        invalidDuration: "Invalid duration",
        invalidVisibility: "Invalid visibility",
        routineTitleRequired: "Each routine needs a title",
        routineTriggerRequired: "Each routine needs a trigger",
        selectAtLeastOneDay: "Select at least one day",
        timesPerWeekRange: "Times per week must be between 1 and 7",
      },
      emptyStateLabel: "battleplan settings missing",
    },
  },
});
