window.appCopy = Object.assign({}, window.appCopy || {}, {
  battleplan: {
    titleBattleplan: "Battleplan",
    archiveLabel: "Archive",
    list: {
      activeSectionLabel: "The Active Plan",
      draftSectionLabel: "Draft",
      archiveSectionLabel: "Archive",
      duplicateLabel: "Duplicate",
      newPlanLabel: "New Plan",
      emptyLabel: "No battleplan yet",
      errorMessage: "Battleplan unavailable.",
      sectionAriaLabel: "Battleplan",
      statusLabels: {
        active: "Active",
        draft: "Draft",
        completed: "Completed",
        archived: "Archived",
      },
      overwriteDraftDialog: {
        title: "You already have an active plan and a draft. Overwrite the draft?",
        cancelLabel: "No",
        confirmLabel: "Yes",
      },
    },
    view: {
      editLabel: "Edit",
      addNoteLabel: "+ Add Note",
      addNoteTitle: "Add battleplan note",
      addNoteSubmitLabel: "Add",
      addNoteEmptyStatus: "Write a note.",
      activateLabel: "Activate",
      deleteLabel: "Delete",
      deleteDialog: {
        title: "Delete this battleplan?",
        cancelLabel: "Cancel",
        confirmLabel: "Delete",
      },
    },
    wizardShared: {
      pillarFallbackLabel: "Pillar",
      pauseRoutineAria: "Pause routine",
      deleteRoutineButtonLabel: "Delete",
      missingPriorityLabel: "Missing Priority",
      errorPrefix: "Error",
      removedRoutinesStatus: {
        singular: "Removed 1 incomplete routine (missing title or trigger).",
        plural: "Removed {count} incomplete routines (missing title or trigger).",
      },
      summaryDurationDays: "{count} days",
      summaryDraftBadge: "DRAFT",
    },
    placeholder: {
      label: "sharpening the blades",
    },
    fab: {
      newAria: "New Battleplan",
    },
    wizard: {
      progressPrefix: "MISSION PHASE",
      statePriority: "PRIORITY",
      nextLabel: "NEXT",
      backLabel: "BACK",
      confirmLabel: "Confirm",
      saveDraftLabel: "Save Draft",
      daysSuffix: "D",
      routineWord: "Routine",
      routineCountWord: "routines",
      labels: {
        priorityField: "Main Priority",
        whyField: "Why",
        durationField: "Priority Duration",
        objectiveField: "Objective",
        titleField: "Title",
        triggerField: "Trigger",
        cadenceField: "Cadence",
        timesPerWeek: "Times per week",
        summaryPriority: "Priority",
        summaryDuration: "Duration",
        summaryVisibility: "Visibility",
        summaryPillars: "Pillars",
      },
      placeholders: {
        priorityTitle: "E.g. Show up for the people I love.",
        priorityWhy: "Define your 'why' to keep course...",
        objective: "Define a concrete and measurable objective",
        routineTitle: "e.g. daily cold shower",
        routineTrigger: "e.g. right after I wake up",
      },
      actions: {
        addRoutine: "+ Add routine",
        removeRoutineAria: "Remove",
        expandRoutineAria: "Expand routine",
        collapseRoutineAria: "Collapse routine",
        deleteRoutine: {
          title: "Delete routine",
          meta: "This action cannot be undone.",
          cancelLabel: "Cancel",
          confirmLabel: "Delete",
        },
        cancelEdit: {
          title: "Are you sure you want to discard your changes?",
          keepLabel: "Keep editing",
          confirmLabel: "Discard changes",
        },
      },
      dayShort: {
        mon: "M",
        tue: "T",
        wed: "W",
        thu: "T",
        fri: "F",
        sat: "S",
        sun: "S",
      },
      errors: {
        saveFailed: "Save failed. Try again.",
        priorityRequired: "Priority is required",
        priorityWhyRequired: "Why is required",
        invalidDuration: "Invalid duration",
        invalidVisibility: "Invalid visibility",
        completePillarRequired: "Add at least one pillar with an objective and one routine",
        pillarObjectiveRequired: "Missing objective",
        pillarRoutineRequired: "Missing routine",
        routineTitleRequired: "Each routine needs a title",
        routineTriggerRequired: "Each routine needs a trigger",
        selectAtLeastOneDay: "Select at least one day",
        timesPerWeekRange: "Times per week must be between 1 and 7",
      },
      emptyStateLabel: "battleplan settings missing",
    },
  },
});
