window.appCopy = Object.assign({}, window.appCopy || {}, {
  events: {
    list: {
      title: "Events",
      futureLabel: "Upcoming",
      pastLabel: "Past",
      emptyLabel: "No events yet",
      errorMessage: "Events unavailable.",
      sectionAriaLabel: "Events",
      statusLabels: {
        upcoming: "Upcoming",
        past: "Past",
      },
      autoTitleFallback: "Event",
      newLabel: "New event",
    },
    detail: {
      registerLabel: "I'll attend",
      unregisterLabel: "Can't make it",
      registrationConfirmed: "You're attending",
      registrationPending: "Awaiting confirmation",
      attendanceTitle: "Attendance",
      markPresent: "Present",
      markAbsent: "Absent",
      clearAttendance: "Clear",
      attendedLabel: "You attended",
      missedLabel: "You missed this one",
      registrationsTitle: "Attendees",
      pastAttendanceTitle: "Mark attendance",
      registerError: "Could not register.",
      unregisterError: "Could not unregister.",
      attendanceError: "Could not update attendance.",
      occurrencesLabel: "Occurrences",
      cancelOccurrenceLabel: "Cancel this one",
      cancelledLabel: "Cancelled",
      pastLabel: "Past",
      cancelOccurrenceConfirm: {
        title: "Cancel this occurrence?",
        confirmLabel: "Cancel occurrence",
      },
      cancelDialog: {
        title: "Cancel this event?",
        confirmLabel: "Cancel event",
        cancelLabel: "Keep event",
      },
    },
    wizard: {
      progressPrefix: "STEP",
      nextLabel: "Next",
      backLabel: "Back",
      confirmLabel: "Create",
      saveLabel: "Save",
      emptyStateLabel: "Events wizard unavailable",
      cancelMeta: "Choose what to cancel.",
      rescheduleTitle: "Reschedule event",
      rescheduleConfirm: "Save",
      scheduleLabels: {
        sun: "Sun",
        mon: "Mon",
        tue: "Tue",
        wed: "Wed",
        thu: "Thu",
        fri: "Fri",
        sat: "Sat",
        position_1st: "1st",
        position_2nd: "2nd",
        position_3rd: "3rd",
        position_4th: "4th",
        position_5th: "5th",
        position_last: "Last",
      },
      steps: {
        type: {
          title: "Event type",
          subtitle: "What kind of event are you creating?",
        },
        group: {
          title: "Pick a group",
          subtitle: "Which group is this event for?",
        },
        dates: {
          title: "When",
          subtitle: "Pick a date and schedule.",
        },
        details: {
          title: "Details",
          subtitle: "Add a title, link, and description.",
        },
        confirm: {
          title: "Confirm",
        },
      },
      labels: {
        scheduleField: "Schedule",
        onceOption: "Once",
        weeklyOption: "Weekly",
        monthlyOption: "Monthly",
        startDateField: "Start date",
        startTimeField: "Time",
        endDateField: "End date",
        weekdayField: "Week day",
        monthPositionField: "Month position",
        monthDayField: "Day",
        countField: "How many",
        previewField: "Preview",
        titleField: "Title",
        locationField: "Location",
        urlField: "Link",
        descriptionField: "Description",
        optionalTag: "(optional)",
        summaryType: "Type",
        summaryGroup: "Group",
        summaryDates: "Dates",
        summaryTitle: "Title",
        summaryLocation: "Location",
        summaryURL: "Link",
        summaryDescription: "Description",
      },
      placeholders: {
        title: "Event title",
        location: "Location",
        url: "https://...",
        description: "Add details or anything attendees should know.",
      },
      actions: {
        cancelEvent: "Cancel event",
        reschedule: "Reschedule",
      },
      errors: {
        typeRequired: "Pick an event type.",
        typeInvalid: "Invalid event type.",
        groupRequired: "Pick a group.",
        startDateRequired: "Pick a start date.",
        startDateInvalid: "Start date must be valid.",
        timeRequired: "Pick a start time.",
        timeInvalid: "Time must be valid.",
        endDateRequired: "Pick an end date.",
        endDateInvalid: "End date must be valid.",
        endDateBeforeStart: "End date must be after start date.",
        scheduleInvalid: "Pick a valid schedule.",
        countInvalid: "Pick a valid count.",
        weekdayInvalid: "Pick a valid day.",
        monthPositionInvalid: "Pick a valid month position.",
        titleRequired: "Title is required for this event type.",
        locationRequired: "Location is required for this event type.",
        urlRequired: "Link is required for this event type.",
        descriptionRequired: "Description is required for this event type.",
        urlInvalid: "Link must be a valid URL.",
        saveFailed: "Save failed. Try again.",
        noAllowedTypes: "You can't create any event type.",
        noEligibleGroups: "No groups available for this event type.",
        eventNotFound: "Event not found.",
      },
    },
  },
});
