// Italian translation of retreats.public. The English copy in copy/retreats.js
// stays the source of truth; this file only overlays the localized strings.
window.appCopyI18n.translate("retreats.public", {
  notFound: "Raduno non trovato.",
  nav: {
    event: "L'evento",
    place: "Il luogo",
    info: "Info pratiche",
    faq: "FAQ",
  },
  hero: {
    kickerFallback: "Raduno",
  },
  stats: {
    when: "Quando",
    where: "Dove",
    duration: "Durata",
    fee: "Quota",
  },
  duration: {
    day: "giorno",
    days: "giorni",
    night: "notte",
    nights: "notti",
  },
  event: {
    eyebrow: "L'evento",
    heading: "Il raduno",
  },
  place: {
    arrivalHeading: "Come arrivare",
    arrivalCar: "In auto",
    arrivalTrain: "In treno",
    arrivalCarpooling: "Car sharing",
  },
  info: {
    eyebrow: "Info pratiche",
    heading: "Cosa portare, cosa è incluso",
    packing: "Da portare",
    included: "Incluso nella quota",
    notIncluded: "Non incluso",
  },
  signup: {
    deadlinePrefix: "Iscrizioni aperte fino al",
    capacityNote: "I posti sono limitati.",
    depositNote: "L'iscrizione si conferma con il versamento dell'acconto.",
    genericNote: "Riserva il tuo posto.",
    contactCta: "Scrivici",
    feeRow: "Quota",
    depositRow: "Acconto",
    depositSuffix: "non rimborsabile",
    balanceRow: "Saldo",
    balanceSuffix: "in struttura",
    minAgeRow: "Età minima",
    submitMember: "Iscriviti",
    submitMemberDeposit: "Iscriviti e versa l'acconto",
    submitGuest: "Iscriviti",
    notOpen: "Le iscrizioni non sono ancora aperte.",
    full: "Posti esauriti.",
    successMember: "Iscrizione ricevuta, controlla la tua email.",
    successGuest: "Pre-iscrizione ricevuta. Ti ricontattiamo noi per confermare il posto.",
    choice: {
      startCta: "Iscriviti",
      question: "Fai parte di un gruppo Realmen?",
      memberCta: "Accedi",
      or: "oppure",
      guestCta: "Prosegui",
    },
    guestNote: "I posti sono limitati. Questa è una pre-iscrizione: ti ricontattiamo noi per confermare il posto.",
    guestFields: {
      fullName: "Nome e cognome",
      fullNamePlaceholder: "Mario Rossi",
      birthYear: "Anno di nascita",
      birthYearPlaceholder: "1985",
      birthYearError: "Anno di nascita non valido.",
      provenance: "Provenienza",
      provenancePlaceholder: "Città o provincia",
      mobile: "Telefono",
      mobilePlaceholder: "+39 333 1234567",
      mobileHint: "Obbligatorio: ti chiamiamo per confermare la pre-iscrizione.",
    },
    errors: {
      alreadySubmitted: "Ti sei già iscritto a questo raduno.",
      closed: "Le iscrizioni sono chiuse.",
      full: "Posti esauriti.",
      invalidEmail: "Email non valida.",
      missingGuestFields: "Compila tutti i campi richiesti.",
      generic: "Iscrizione non riuscita, riprova.",
    },
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Domande frequenti",
  },
});
